module.exports = {
  machinery: [
    {
      // id: "1",
      name: "Combine Harvester",
      crop: { paddy: "paddy", wheat: "wheat" },
      crops: ["paddy", "wheat"],
      use: "Cutting of paddy,Sorting and cleaning grains",
      description: "Self propelled full feeding with auger spike threshing",
      phaseofcrop: "Harvesting",
      manufactured: "Darsh Palesse",
      model: "GS575",
      price: 2410000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/SELLER/Default/2020/8/RI/YG/DX/112029108/gt-6-500x500.png",
      youtube: "https://youtu.be/xi6PwVlM74U",
      website:
        "https://www.indiamart.com/proddetail/gomselmash-paddy-combine-harvester-22562420997.html",
    },

    // {
    //   // id: "2",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Mahindra",
    //   model: "Mahindra jivo 225DI",
    //   price: 450000,
    //   prebuilt: "yes",
    //   image:
    //     "https://www.tractorjunction.com/assets/images/upload/575-di-1586002666.jpg",
    //   youtube: "https://youtu.be/4zZR-D0MbtA",
    //   website: "https://www.mahindratractor.com/",
    // },
    // {
    //   // id: "3",
    //   name: "Transplanter",
    //   // crops: "Paddy,wheat",
    //   crop: {
    //     paddy: "paddy",
    //     wheat: "wheat",
    //   },
    //   crops: ["paddy", "wheat"],
    //   use: "Transplanting seedlings into the field",
    //   description:
    //     "Automatic float adjustment mechanism for uniform depths for high yield.",
    //   phaseofcrop: "Sowing",
    //   manufactured: "Mahindra",
    //   model: "MP461",
    //   price: 230000,
    //   prebuilt: "yes",
    //   image:
    //     "https://img1.exportersindia.com/product_images/bc-full/2019/5/1045352/manual-rice-transplanter-1556713186-4884230.jpeg",
    //   youtube: "https://youtu.be/NGqlVSx-z1Y",
    //   website: "https://www.deere.co.in/en/implements/laser-leveler/",
    // },
    // {
    //   // id: "4",
    //   name: "Leveller",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Levelling of soil",
    //   description: "Laser guided soil leveller",
    //   phaseofcrop: "soil preparation",
    //   manufactured: "John Deere",
    //   model: "LL1117",
    //   price: 250000,
    //   prebuilt: "yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/Laser_Leveler_large_e90a1ebc5a42890049433807f52aaf9fe647a244.png",
    //   youtube: "https://youtu.be/RXVN2oZmNf4",
    //   website: "https://www.deere.co.in/en/implements/laser-leveler/",
    // },
    // {
    //   // id: "5",
    //   name: "Rice cutting machine",
    //   // crops: "Paddy,wheat",
    //   crop: {
    //     paddy: "paddy",
    //     wheat: "wheat",
    //   },
    //   crops: ["paddy", "wheat"],
    //   use: "cutting grains from the crop",
    //   description: "is suitable for cutting all kinds of crops",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "Vardhman",
    //   model: "Power Reaper",
    //   price: 115000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/ND/FB/MY-10411868/2fd-soya-vardhman-power-reapers-500x500.jpg",
    //   youtube: "https://youtu.be/RXVN2oZmNf4",
    //   website: "https://www.deere.co.in/en/implements/laser-leveler/",
    // },
    // {
    //   // id: "6",
    //   name: "Destoner",
    //   // crops: "Paddy",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use: "Separating stones and broken rice from the rice",
    //   description: "Is suitable for all kind of grains",
    //   phaseofcrop: "After harvesting",
    //   manufactured: "Damodar process plant pvt ltd",
    //   model: "2MT",
    //   price: 110000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/LR/OB/HZ/SELLER-9040957/tea-destoner-500x500.jpg",
    //   youtube: "https://youtu.be/1c9w3JrxcGc",
    //   website: "",
    // },
    // {
    //   // id: "7",
    //   name: "Rice mill",
    //   // crops: "Paddy",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],

    //   use: "Paddy is processed to rice",
    //   description: "Produce edible milled rice and separates the husk",
    //   phaseofcrop: "After harvesting",
    //   manufactured: "Agripro",
    //   model: "Agripro 3hp Butterfly",
    //   price: 190000,
    //   prebuilt: "yes",
    //   image:
    //     "https://i.pinimg.com/564x/18/e6/b7/18e6b7c930b20846d04204a8fb6370f2.jpg",
    //   youtube: "https://youtu.be/TfD5Uhg3JHo",
    //   website: "",
    // },
    // {
    //   // id: "8",
    //   name: "Polisher",
    //   // crops: "Paddy",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],

    //   use: "Transforming brown rice into white rice",
    //   description: "Easy to use, operate and carry. Low maintenance.",
    //   phaseofcrop: "After harvesting",
    //   manufactured: "Sun Agro",
    //   model: "Butterfly Model",
    //   price: 25000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/NQ/EU/QT/ANDROID-6423016/product-jpeg-500x500.jpg",
    //   youtube: "https://youtu.be/g1TOIhusP_0",
    //   website: "http://www.sunagrobhilai.com/",
    // },
    // {
    //   // id: "9",
    //   name: "Furrow Opener",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Makes straight and deep furrow by pressuring with opening blade",
    //   description: "Furrow Opener Cum Ridger",
    //   phaseofcrop: " seedling",
    //   manufactured: "Sudha Agro Industries",
    //   model: "5 Tyne Furrow Opener Cum Ridger",
    //   price: 38000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/MI/GT/ND/SELLER-2292693/7-tyne-tractor-operated-cultivator-500x500.jpg",
    //   youtube: "",
    //   website: "",
    // },
    // {
    //   // id: "10",
    //   name: "Plough",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Loosening or turning the soil before sowing seed or planting",
    //   description:
    //     "Large farming tool with sharp blades which is pulled across the soil",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Mahindra",
    //   model: "Rigid Tyne Shovel Type",
    //   price: 18500,
    //   prebuilt: "yes",
    //   image:
    //     "https://3.imimg.com/data3/KQ/IF/MY-7704388/bedder-plough-500x500.jpg",
    //   youtube: "https://youtu.be/MgIDOovFT5A",
    //   website: "https://www.bharatsteelwork.com/",
    // },
    // {
    //   // id: "11",
    //   name: "Rice Huller",
    //   crops: "paddy",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use: "Automate the process of removing the chaff of grains of rice.",
    //   description:
    //     "Uses an abrasive rotating disk to first remove the husk before passing the grain to conical rollers",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "Nans",
    //   model: "Rice huller without stand",
    //   price: 16000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/HZ/JZ/BV/SELLER-3213215/rice-huller-with-polisher-blower-attached-500x500.jpg",
    //   youtube: "https://youtu.be/RGA77K6XUzw",
    //   website: "https://www.thomaseximp.com/rice%20%26%20maize.html",
    // },
    // {
    //   // id: "12",
    //   name: "Thresher",
    //   crops: "paddy",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use:
    //     "Threshes the grain by beating the plant to make the seeds fall out.",
    //   description: "Suitable for multi crop threshing",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "Mahindra",
    //   model: "Paddy thresher",
    //   price: 135000,
    //   prebuilt: "yes",
    //   image:
    //     "https://5.imimg.com/data5/SELLER/Default/2020/9/PY/PF/NJ/15747168/thresher-m55-500x500.jpg",
    //   youtube: "https://youtu.be/ZxvkBNPlwKQ",
    //   website:
    //     "https://www.machinenmotor.com/details/mahindra-mild-steel-multi-crop-thresh",
    // },
    // {
    //   // id: "13",
    //   name: "Weeder",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Removing weeds and clearing the soil",
    //   description: "Adjustable handlebar to meet different requirements",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Agripro",
    //   model: "APC95FQ",
    //   price: 27500,
    //   prebuilt: "yes",
    //   image:
    //     "https://cdn1.industrybuying.com/products_medium/agriculture-garden-landscaping/tillers-and-cultivator/cultivator/AGR.CUL.42018780_1547458842273.jpg",
    //   youtube: "https://youtu.be/rV3b2ucMTls",
    //   website: "https://www.agri-pro.com/",
    // },
    // {
    //   // id: "14",
    //   name: "Pulverizer",
    //   crops: "paddy",
    //   crop: {
    //     paddy: "paddy",
    //     wheat: "wheat",
    //     turmeric: "turmeric",
    //     ragi: "ragi",
    //     spices: "spices",
    //   },
    //   crops: ["paddy", "wheat", "turmeric", "ragi", "spices"],
    //   use:
    //     " machinery for wheat grinding, turmeric grinding, rice grinding, ragi grinding, spices grinding",
    //   description:
    //     "mechanical device for the grinding of many different types of materials",
    //   phaseofcrop: "After Harvesting",
    //   manufactured: "S.K.Engineers",
    //   model: "S.K.Engineers",
    //   price: 60000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/EB/UG/NR/SELLER-3158394/grinder-500x500.jpg",
    //   youtube: "https://youtu.be/Vn82kiY67aY",
    //   website: "https://www.skengineer.org/search.html?ss=rice+pulverizers",
    // },
    // {
    //   // id: "15",
    //   name: "Tiller ",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: " used to prepare soil for cultivating and planting",
    //   description:
    //     "have excellent penetration, light on tractor, heavy on soil",
    //   phaseofcrop: "land preparation",
    //   manufactured: "Bharat Industries",
    //   model: "Bharat",
    //   price: 64000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://2.imimg.com/data2/OS/NN/MY-704816/rotary-tiller-rotaverter-500x500.jpg",
    //   youtube: "https://youtu.be/I8pPBcX3mf0",
    //   website: "https://www.bharatagri.net/agricultural-implements.html",
    // },
    // {
    //   // id: "16",
    //   name: "Cultivator",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "to cultivate lands before farming",
    //   description: "Suitable for inter-culture operations",
    //   phaseofcrop: "land preparation",
    //   manufactured: "Mahindra",
    //   model: "Cultivator",
    //   price: 15000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.tractorjunction.com/assets/images/images/implementTractor/rigid-cultivator-karc-0954636.jpg",
    //   youtube: "https://youtu.be/I3bgFWYYSQg",
    //   website: "https://www.tractorjunction.com/implement/mahindra/cultivator/",
    // },
    // {
    //   // id: "17",
    //   name: "Tractor",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land Preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Mahindra",
    //   model: "GYROVATOR SLX",
    //   price: 180000,
    //   prebuilt: "Yes",
    //   image: "https://4.imimg.com/data4/DX/XC/GLADMIN-11102942/1-500x500.jpg",
    //   youtube: "https://www.youtube.com/watch?v=4zZR-D0MbtA",
    //   website:
    //     "https://www.mahindratractor.com/tractors-implements/gyrovator-slx",
    // },
    // {
    //   // id: "18",
    //   name: "Tractor",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land Preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Mahindra",
    //   model: "GYROVATOR ZLX",
    //   price: 150000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.m2all.com/media/catalog/product/cache/1/image/300x300/9df78eab33525d08d6e5fb8d27136e95/s/l/slx_1_4.jpg",
    //   youtube: "https://www.youtube.com/watch?v=4zZR-D0MbtA",
    //   website:
    //     "https://www.mahindratractor.com/tractors-implements/gyrovator-zlx",
    // },
    // {
    //   // id: "19",
    //   name: "Potato Planter",
    //   crop: {
    //     potato: "potato",
    //   },
    //   crops: ["potato"],
    //   use: "Supplies potatoes to the planting belt in a consistent manner",
    //   description: "Moving floor and variety of holding cups",
    //   phaseofcrop: "Planting",
    //   manufactured: "Mahindra",
    //   model: "Mahindra Potato Planter",
    //   price: 500000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/VD/IN/MY-20902397/potato-planter-500x500.jpg",
    //   youtube: "https://youtu.be/LJPlJFo4jWI",
    //   website:
    //     "https://www.mahindratractor.com/tractors-implements/potato-planter",
    // },
    // {
    //   // id: "20",
    //   name: "Tractor",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land Preparation",
    //   description: "high max torque and excellent backup torque",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Mahindra",
    //   model: "Mahindra 275 TU XP Plus",
    //   price: 690000,
    //   prebuilt: "Yes",
    //   image: "https://cdn.tractorguru.com/upload/mahindra-475-di-xp-plus.jpg",
    //   youtube: "https://youtu.be/21bTgENOwtw",
    //   website:
    //     "https://www.mahindratractor.com/tractors/mahindra-275-tu-xp-plus",
    // },
    // {
    //   // id: "21",
    //   name: "Tractor",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "land Preparation",
    //   description: "high max torque and excellent backup torque",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Mahindra",
    //   model: "Mahindra 275 DI SP Plus",
    //   price: 600000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.tractorjunction.com/assets/images/upload/mahindra-475-di-xp-plus.jpg",
    //   youtube: "https://youtu.be/21bTgENOwtw",
    //   website:
    //     "https://www.mahindratractor.com/tractors/mahindra-275-di-sp-plus",
    // },
    // {
    //   // id: "22",
    //   name: "Power Sprayer",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Spraying fertilizers and chemicals",
    //   description: "tank capacity of 25l",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Honda",
    //   model: "WJR2525T",
    //   price: 29000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://global.honda/content/dam/site/global/newsroom/cq_img/worldnews/2014/c140825/02.jpg",
    //   youtube: "https://youtu.be/vxi-bgwvRe8",
    //   website: "https://www.hondaindiapower.com/product-detail/wjr2525t",
    // },
    // {
    //   // id: "23",
    //   name: "Sprayer Pump",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Spraying fertilizers and chemicals",
    //   description: "Capable of very high pressure.",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Neptune",
    //   model: "PW-768 A",
    //   price: 7500,
    //   prebuilt: "Yes",
    //   image:
    //     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeZVLIG38LZc_-6_hvfTgCpb5xkj4PYw0DW2kWeQMJ5zOHmLSZZccwfmwffZFcon19eOemb84&usqp=CAc",
    //   youtube: "https://youtu.be/BPBFGUXyk8A",
    //   website: "https://www.neptunesprayers.in/",
    // },
    // {
    //   // id: "24",
    //   name: "Fertilizer Drill",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Spreading fertilizer",
    //   description: "seed cum fertilizer drill",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "Kovai classic industries",
    //   model: "KCI",
    //   price: 68000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://tiimg.tistatic.com/fp/2/005/373/seed-cum-fertilizer-drill-9-tyne-348.jpg",
    //   youtube: "https://youtu.be/VsQaoW6HSgI",
    //   website: "https://www.kovaiclassicindustries.net/seed-drills.html",
    // },
    // {
    //   // id: "25",
    //   name: "Mist blower",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use:
    //     "used for projection of water, weed killers, crop performance materials, pest",
    //   description: "holds capacity of 14l",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "STIHL",
    //   model: "SR5600",
    //   price: 16500,
    //   prebuilt: "Yes",
    //   image:
    //     "https://static.stihl.com/upload/assetmanager/modell_imagefilename/scaled/websize/e8781f09b0fb4d47845c359e77136910.jpg",
    //   youtube: "https://youtu.be/ixWaV0Cjl8g",
    //   website:
    //     "https://www.stihl.com/STIHL-power-tools-A-great-range/Mistblowers-and-sprayer",
    // },
    // {
    //   // id: "26",
    //   name: "Motorized weeder",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Removing weeds",
    //   description: "Adjustable motor to meet different requirements",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "JJR Agriculture & Packaging System",
    //   model: "NC-52T",
    //   price: 18000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/SELLER/Default/2020/9/DB/TP/QV/38051033/nc-52b-neptune-sprayers-500x500-1-500x500.jpg",
    //   youtube: "https://youtu.be/Y8XqC-nnUv0",
    //   website: "http://jjragroandpack.com/product/nc-62-weeders/",
    // },
    // {
    //   // id: "27
    //   name: "Wheel Hoe",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "To shape soil",
    //   description: "Adjustable handlebar to meet different requirements",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Mahan",
    //   model: "Mahan wheel hoe",
    //   price: 5550,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/XW/CO/FR/SELLER-3538146/manual-wheel-hoe-with-oscillating-hoe-6-8-12-in-redger-bund-former-cultivation-teeth-4-marker-500x500.jpg",
    //   youtube: "https://www.youtube.com/watch?v=ccRyZR53Qcw",
    //   website:
    //     "https://www.indiamart.com/proddetail/manual-wheel-hoe-with-oscillating-hoe-22409142373.html",
    // },
    // {
    //   // id: "28",
    //   name: "Cono Weeder",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "to remove weeds and clearing soil",
    //   description: "mini weeder",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Vinglob greentech pvt ltd",
    //   model: " VGT- CW-1",
    //   price: 1550,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/SELLER/Default/2021/2/CC/YG/QF/68948032/cono-weeder-500x500.jpg",
    //   youtube: "https://www.youtube.com/watch?v=c3RLZtaCE-A",
    //   website: "https://www.vinglobgreentechindia.com/agriculture-weeder.html",
    // },
    // {
    //   // id: "29",
    //   name: "Corn Planter",
    //   crop: {
    //     Corn: "Corn",
    //     Maize: "Maize",
    //   },
    //   crops: ["Corn", "Maize"],
    //   use: "Planters lay the seeds down in precise manner along rows.",
    //   description: "multi crop planter",
    //   phaseofcrop: "sowing",
    //   manufactured: "National Agro Industries",
    //   model: "NMCP",
    //   price: 50000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/QE/OL/MY-192022/corn-planter-500x500.jpg",
    //   youtube: "https://youtu.be/9QhdtU1wTRk",
    //   website: "https://www.nationalagro.com/our-products.php",
    // },
    // {
    //   // id: "30",
    //   name: "Sugarcane Planter",
    //   crop: {
    //     sugarcane: "sugarcane",
    //   },
    //   crops: ["sugarcane"],
    //   use:
    //     "The Planter Mekes furrow, cuts the sugarcane into setts & deposit sets in the furrow.",
    //   description: "Tractor Operated Pit Digger for Sugar Cane Planting",
    //   phaseofcrop: "furrowing",
    //   manufactured: "Rohitkrishi industries",
    //   model: "Rohitkrishi indusries",
    //   price: 13500,
    //   prebuilt: "Yes",
    //   image: "http://rohitkrishi.com/img/2-row-sugarcane-planter.jpg",
    //   youtube: "http://rohitkrishi.com/videos.html",
    //   website: "http://www.rohitkrishi.com/2-row-sugarcane-planter.html",
    // },
    // {
    //   // id: "31",
    //   name: "Bed Planter",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "used for planting different seeds on 2 Raised beds.",
    //   description:
    //     "Bed Making & Sowing on the tip of the bed is done in single operation.",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "National Agro Industries",
    //   model: "NRBP",
    //   price: 65000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/DG/XB/YU/SELLER-80186678/raised-bed-planter-250x250.jpg",
    //   youtube: "",
    //   website:
    //     "https://www.nationalagro.com/product/national-raised-bed-planter",
    // },
    // {
    //   // id: "32",
    //   name: "Maize sheller",
    //   crop: {
    //     maize: "maize",
    //   },
    //   crops: ["maize"],
    //   use: " shelling Maize from cobs",
    //   description: " very easily transportable because of three-point linkage.",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "National Agro Industries",
    //   model: "NMS",
    //   price: 20000,
    //   prebuilt: "Yes",
    //   image: "https://tiimg.tistatic.com/fp/1/344/maize-sheller-217.jpg",
    //   youtube: "https://youtu.be/Kc5JloW2Ziw",
    //   website: "https://www.nationalagro.com/product/national-maize-sheller",
    // },
    // {
    //   // id: "33",
    //   name: "Seed Drill",
    //   crop: {
    //     allgrains: "allgrains",
    //     paddy: "Paddy",
    //     wheat: "wheat",
    //     maize: "maize",
    //     pulses: "pulses",
    //   },
    //   crops: ["allgrains", "Paddy", "wheat", "maize", "pulses"],
    //   use: "For sowing different crops",
    //   description:
    //     " side wheel driving mechanism & central wheel driving mechanism.",
    //   phaseofcrop: "Sowing",
    //   manufactured: "Lalwani industries",
    //   model: "Lalwani",
    //   price: 44000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/CA/AS/MY-8964291/seed-drill-500x500.jpg",
    //   youtube: "https://youtu.be/d3VscbsW6Jk",
    //   website: "http://lalwanikrishiyantra.com/Product_Controllers/product/2",
    // },
    // {
    //   // id: "34",
    //   name: "Manual Drawn planter",
    //   crop: {
    //     allgrains: "allgrains",
    //     paddy: "paddy",
    //     wheat: "wheat",
    //     maize: "maize",
    //     pulses: "pulses",
    //   },
    //   crops: ["allgrains", "Paddy", "wheat", "maize", "pulses"],
    //   use: "Precise distance between two seeds",
    //   description: "Suitable for small and marginal farm",
    //   phaseofcrop: "Sowing",
    //   manufactured: "Rohitkrishi industries",
    //   model: "",
    //   price: 8000,
    //   prebuilt: "Yes",
    //   image: "http://www.rohitkrishi.com/img/row-mannual-drawn-machine.jpg",
    //   youtube: "https://youtu.be/a2RIuT3lsEU",
    //   website: "http://www.rohitkrishi.com/row-mannual-drawn.html",
    // },
    // {
    //   // id: "35",
    //   name: "Sub soiler",
    //   crop: {
    //     sugarcane: "sugarcane",
    //     pulses: "pulses",
    //     cotton: "cotton",
    //   },
    //   crops: ["sugarcane", "pulses", "cotton"],
    //   use: "for deep tillage to loosen and break up the hard pan in the soil.",
    //   description: "works best in medium and hard type of soil.",
    //   phaseofcrop: "Cultivation",
    //   manufactured: "John Deere",
    //   model: "Greensystem subsoiler",
    //   price: 60000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/Implement_sub_soiler_large_dc85eadfbc4b8ef3d88f072e3ca78ece1fce95a7.png",
    //   youtube: "https://youtu.be/jnlZmkdpmAg",
    //   website: "https://www.deere.co.in/en/implements/subsoiler/",
    // },
    // {
    //   // id: "36",
    //   name: "Check basin former",
    //   // crops: "All",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "effective for land preparation",
    //   description: "Maximum labour utilization",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "Greensystem check basin former",
    //   price: 110000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/john_deere_tractors_green_system_implement_Check_Basin_Former__large_095f882794fa5f79bc619894a8297d0140fda271.png",
    //   youtube: "https://youtu.be/p8gp-SWmNMM",
    //   website: "https://www.deere.co.in/en/implements/checkbasinformer/",
    // },
    // {
    //   // id: "37",
    //   name: "Ratoon manager",
    //   crop: {
    //     sugarcane: "sugarcane",
    //   },
    //   crops: ["sugarcane"],
    //   use:
    //     "helps in managing the Sugarcane crop and facilitates ratoon crop for the next season.",
    //   description:
    //     "Efficient Labour Utilization,Shaving of stubbles at ground level,Effective cleaning of field and removal of dead canes, trash",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "John Deere",
    //   model: "Greensystem Ratoon manager",
    //   price: 42000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/ratoon_manager_large_2e687d779c2534118b4c00cc8a61bf6039518b93.png",
    //   youtube: "https://youtu.be/a0DNJf2JaN4",
    //   website: "https://www.deere.co.in/en/implements/ratoon-manager/",
    // },
    // {
    //   // id: "38",
    //   name: "Vaccum planter",
    //   crop: {
    //     Cottons: "Cottons",
    //     Corns: "Corns",
    //     Soybeans: "Soybeans",
    //     Grains: "Grains",
    //   },
    //   crops: ["Cottons", "Corns", "Soybeans", "Grains"],
    //   use:
    //     "provides high accuracy in the sowing of multiple crops like Cotton, Corn, Soybean and Grains.",
    //   description:
    //     "High rate of germination of seeds,Low expenses on maintenance",
    //   phaseofcrop: "Sowing and planting",
    //   manufactured: "John Deere",
    //   model: "Green system multicrop vaccum planter",
    //   price: 110000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/Multi_Crop_Vacuum_Planter_Greensystem_large_375f5226686445207d89ebe91784bc0e18e4d422.png",
    //   youtube: "https://youtu.be/j9UW9V-h3lk",
    //   website:
    //     "https://www.deere.co.in/en/implements/multicrop-vacuum-planter/",
    // },
    // {
    //   // id: "39",
    //   name: "Hole Digger",
    //   crop: {
    //     Mango: "Mango",
    //     Coconut: "Coconut",
    //     Pomegranate: "Pomegranate",
    //     Teak: "Teak",
    //     Lemon: "Lemon",
    //     CustardApple: "Custard apple",
    //   },
    //   crops: [
    //     "Mango",
    //     "Coconut",
    //     "Pomegranate",
    //     "Teak",
    //     "Lemon",
    //     "Custard apple",
    //   ],
    //   use: " digs pits for plantation and farm fencing purposes ",
    //   description: "Robust & highly efficient single speed gear box",
    //   phaseofcrop: "Land preparation,Plantation",
    //   manufactured: "John Deere",
    //   model: "Greensystem post hole digger",
    //   price: 85000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/Post_Hole_Digger_Implement_Green_system_John_Deere_large_846783987a8f7ffe0eb6a458908e85bedbf89fd6.png",
    //   youtube: "https://youtu.be/DY-qrNJ8jjI",
    //   website: "https://www.deere.co.in/en/implements/post-hole-digger/",
    // },
    // {
    //   // id: "40",
    //   name: "Hydraulic Reversible MB Plough",
    //   crop: {
    //     Sugarcane: "Sugarcane",
    //     Grains: "Grains",
    //     Oilseeds: "Oilseeds",
    //     Pulses: "Pulses",
    //     Cotton: "Cotton",
    //   },
    //   crops: ["Sugarcane", "Grains", "Oilseeds", "Pulses", "Cotton"],
    //   use: "land Preparation",
    //   description:
    //     "Adjustable Soil Inversion Turnbuckle,Optiquick Adjustment Mechanism",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Hydraulic Reversible MB Plough",
    //   price: 325000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/ON/MN/QL/SELLER-40736478/hydraulic-reversible-mb-plough-john-deere-500x500.jpg",
    //   youtube: "https://youtu.be/P5EJAjiNOIE",
    //   website:
    //     "https://www.deere.co.in/en/implements/hydraulic-reversible-plough/",
    // },
    // {
    //   // id: "41",
    //   name: "Chisel Plough",
    //   crop: {
    //     cotton: "cotton",
    //     sugarcane: "sugarcane",
    //     wheat: "wheat",
    //     potatoes: "potatoes",
    //     soybean: "soybean",
    //     pulses: "pulses",
    //   },
    //   crops: ["cotton", "sugarcane", "wheat", "potatoes", "soybean", "pulses"],
    //   use: "land Preparation",
    //   description:
    //     "Efficient upturn of soil with crop stubble,Narrow shovel head can penetrate any type of soil with ease.",
    //   phaseofcrop: "land preparation",
    //   manufactured: "John Deere",
    //   model: "Green System Chisel Plough",
    //   price: 89999,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/YL/KL/WO/SELLER-40736478/green-system-chisel-plough-john-deere-500x500.jpg",
    //   youtube: "https://youtu.be/qywkIawCBis",
    //   website: "https://www.deere.co.in/en/implements/chisel-plough/",
    // },
    // {
    //   // id: "42",
    //   name: "Flail Mower",
    //   crop: {
    //     Grapes: "Grapes",
    //     Pomegranate: "Pomegranate",
    //     Apple: "Apple",
    //     Orange: "Orange",
    //   },
    //   crops: ["Grapes", "Pomegranate", "Apple", "Orange"],
    //   use: "residue management in Orchards and Vineyards.",
    //   description:
    //     "It chops up the left-over crop residue into small pieces leading to easy decomposition near root zone.",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Flail Mower",
    //   price: 110000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/RE/ME/XP/SELLER-40736478/green-system-flail-mower-john-deere-500x500.jpg",
    //   youtube: "https://youtu.be/7ECfPIojZDY",
    //   website: "https://www.deere.co.in/en/implements/flail-mower/",
    // },
    // {
    //   // id: "43",
    //   name: "Mulcher",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use:
    //     "increases crop productivity and converts the cut paddy straw into natural manure.",
    //   description:
    //     "Increased efficiency and higher time saving,Increased efficiency and higher time saving",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Mulcher",
    //   price: 150000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/John_Deere_Green_System_Mulcher_Implement_large_18550a71f3da5e8fcd5ae27694a052ac2afbcc32.png",
    //   youtube: "https://youtu.be/lryb0pbyNTg",
    //   website: "https://www.deere.co.in/en/implements/mulcher/",
    // },
    // {
    //   // id: "44",
    //   name: "Puddler leveler",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use: "preparing the seedbed for transplanting rice",
    //   description: "Enhances crop growth and ensures higher production",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Puddler Leveler",
    //   price: 45000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/MF/OZ/WS/SELLER-6037891/untitled-500x500.png",
    //   youtube: "https://youtu.be/aUeSR88vyEo",
    //   website: "https://www.deere.co.in/en/implements/puddler-leveler/",
    // },
    // {
    //   // id: "45",
    //   name: "Roto Seeder",
    //   crop: {
    //     wheat: "wheat",
    //   },
    //   crops: ["wheat"],
    //   use: "assists in the sowing of wheat seeds.",
    //   description: "efficient farm implement for sowing and planting",
    //   phaseofcrop: "Sowing",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Roto Seeder",
    //   price: 160000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/John_Deere_Roto_Seeder__Greensystem__Implement_large_ee1be813b435c3785b8c64e37dc4bd2b698875e8.png",
    //   youtube: "https://youtu.be/akR7ptozCFk",
    //   website: "https://www.deere.co.in/en/implements/roto-seeder/",
    // },
    // {
    //   // id: "46",
    //   name: "Power Harrow",
    //   crop: {
    //     wheat: "wheat",
    //     Corn: "Corn",
    //     Sugarcane: "Sugarcane",
    //     Millets: "Millets",
    //     Pulses: "Pulses",
    //     Oilseeds: "Oilseeds",
    //   },
    //   crops: ["wheat", "Corn", "Sugarcane", "Millets", "Pulses", "Oilseeds"],
    //   use:
    //     "Reduces the multiple passes that are needed for Seedbed Preparation.",
    //   description:
    //     "Provides better soil structure, resulting in increase of the water holding capacity",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "GreenSystem Power Harrow",
    //   price: 110000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/region-1/products/implements/John_Deere_Green_System_Power_Harrow_large_764a640f59a514eb2567d60c8de53ef54c6b7279.png",
    //   youtube: "https://youtu.be/GgBFHmNtIpk",
    //   website: "https://www.deere.co.in/en/implements/power-harrow/",
    // },
    // {
    //   // id: "47",
    //   name: "Air Blast Sprayer",
    //   crop: {
    //     Grapes: "Grapes",
    //     Pomegranate: "Pomegranate",
    //     Apple: "Apple",
    //     Orange: "Orange",
    //   },
    //   crops: ["Grapes", "Pomegranate", "Apple", "Orange"],
    //   use: " spraying of agro-chemicals onto the crops. ",
    //   description:
    //     "Precision spraying that lowers the overall expenses on Pesticides & Fungicides",
    //   phaseofcrop: "Spraying",
    //   manufactured: "John Deere",
    //   model: "John Deere Air Blast Sprayer ",
    //   price: 120000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/implements/air-blast-sprayer/john_deere_air_blast_sprayer_large_2f25fcbc99b633fd90e41cf3211c1ff35dd9417d.png",
    //   youtube: "https://youtu.be/VKETRLbShcw",
    //   website: "https://www.deere.co.in/en/implements/air-blast-sprayer/",
    // },
    // {
    //   // id: "48",
    //   name: "MouldBoard Plough",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Well suited for tough ploughing job with outstanding depth of cut.",
    //   description:
    //     "The under beam and longitudinal clearance are adequate to cope with trashy conditions.",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "TAFE",
    //   model: "230MS",
    //   price: 45000,
    //   prebuilt: "Yes",
    //   image: "https://www.tafe.com/implements/thumb/mouldboard-plough.png",
    //   youtube: "https://youtu.be/W2l5cTAMcXY",
    //   website: "https://www.tafe.com/implements/Mouldboard-Plough-3-Furrow.php",
    // },
    // {
    //   // id: "49",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Sonalika",
    //   model: "Dual plate clutch 75N",
    //   price: 700000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.tractorjunction.com/assets/images/upload/sonalika-worldtrac-75-rx-2wd-4wd-787318.jpg",
    //   youtube: "https://youtu.be/STfQoZ-tnMg",
    //   website: "https://www.sonalika.com/csr.html",
    // },
    // {
    //   // id: "50",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Escort",
    //   model: "439 Plus",
    //   price: 600000,
    //   prebuilt: "Yes",
    //   image: "https://5.imimg.com/data5/HX/IS/GY/GLADMIN-12/1.jpg",
    //   youtube: "https://youtu.be/KfkMTgdU5fo",
    //   website:
    //     "https://www.farmtracglobal.com/products/tractors/farmtrac-series.html",
    // },
    // {
    //   // id: "51",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "Escort",
    //   model: "Farmtrac70",
    //   price: 495000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://img.agriexpo.online/images_ag/photo-g/182794-12449042.jpg",
    //   youtube: "https://youtu.be/KfkMTgdU5fo",
    //   website:
    //     "https://www.farmtracglobal.com/products/tractors/farmtrac-series.html",
    // },
    // {
    //   // id: "52",
    //   name: "Rice Transplanter",
    //   crop: {
    //     paddy: "paddy",
    //   },
    //   crops: ["paddy"],
    //   use: "Rice transplanting",
    //   description: "Reducing labor and increasing efficiency",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "Kubota",
    //   model: "NSPU-68CMD",
    //   price: 1850000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://sc02.alicdn.com/kf/Headf0627a5004e37b111124a675132aaD/229807408/Headf0627a5004e37b111124a675132aaD.jpg_.webp",
    //   youtube: "https://youtu.be/5KDxXkYtIUA",
    //   website: "https://www.kubota.com/products/farm-m/index.html",
    // },
    // {
    //   // id: "53",
    //   name: "Sugarcane Harvester",
    //   crop: {
    //     sugarcane: "sugarcane",
    //   },
    //   crops: ["sugarcane"],
    //   use: "Cuttingdown Sugarcane",
    //   description: "Precise monitor of operation and monitoring",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "CASEIH",
    //   model: "CASE IH SUGARCANE HARVESTER",
    //   price: "No price",
    //   prebuilt: "Yes",
    //   image:
    //     "https://assets.cnhindustrial.com/caseih/APAC/APACASSETS/Products/Harvesters/Sugar-Cane-Harvester-Austoft-4000/Features/a4000-features-01-1.jpg?width=630&height=350",
    //   youtube: "https://youtu.be/Zn4e7J1VvNU",
    //   website:
    //     "https://www.caseih.com/apac/en-in/products/harvesters#harvesting",
    // },
    // {
    //   // id: "54",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "HMT",
    //   model: "HMT 3522 tractor",
    //   price: 120000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://i.pinimg.com/originals/19/bc/95/19bc95b5afa1605b434538ed549a199c.jpg",
    //   youtube: "https://www.youtube.com/watch?v=g6tx48K06-M",
    //   website: "",
    // },
    // {
    //   // id: "55",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "New Holland",
    //   model: "55HP NEW HOLLAND 5500 TURBO SUPER",
    //   price: 750000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/WQ/QS/MY-46044603/new-holland-3630-tx-super-tractor-500x500.png",
    //   youtube: "https://youtu.be/kbDli0BrXgM",
    //   website:
    //     "https://agriculture.newholland.com/apac/en-in/equipment/products/agricultural-tractors/5500-turbo-sup",
    // },
    // {
    //   // id: "56",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Exception built and performance on rugged and unforgiving terrains",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "New Holland",
    //   model: "New Holland TD5.90",
    //   price: 2575000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://assets.cnhindustrial.com/nhag/apac/en-in/assets/tractors/td5-90/gallery/td5-gallery-02.jpg",
    //   youtube: "https://youtu.be/7jKVGLqNlCY",
    //   website:
    //     "https://agriculture.newholland.com/apac/en-in/equipment/products/agricultural-tractors/td5-90",
    // },
    // {
    //   // id: "57",
    //   name: "Pneumatic Planter",
    //   crop: {
    //     seeds: "seeds",
    //   },
    //   crops: ["seeds"],
    //   use:
    //     "Uniform depth of sowing- better stand, better root growth and no waviness- better yield.",
    //   description: "Precision in sowing I 0-15% increase in the yield",
    //   phaseofcrop: "Sowing",
    //   manufactured: "New Holland",
    //   model: "PP400",
    //   price: 550000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/SJ/XY/SF/SELLER-7834198/maize-planter-pneumatic-500x500.jpeg",
    //   youtube: "https://youtu.be/cv1SjOOo7uQ",
    //   website:
    //     "https://agriculture.newholland.com/apac/en-in/equipment/products/hay-forage/pneumatic-planter",
    // },
    // {
    //   // id: "58",
    //   name: "Forage Harvester",
    //   crop: {
    //     barley: "barley",
    //     corn: "corn",
    //     grass: "grass",
    //   },
    //   crops: ["barley", "corn", "grass"],
    //   use: "Making silage of all types of green feed plants",
    //   description:
    //     "More powerful and efficient, while maintaining high-quality silage",
    //   phaseofcrop: "Harvesting",
    //   manufactured: "John Deere",
    //   model: "FT40",
    //   price: 3020000,
    //   prebuilt: "Yes",
    //   image:
    //     "https://img.agriexpo.online/images_ag/photo-m2/169144-10274377.jpg",
    //   youtube: "https://youtu.be/xvdGnyWV7pI",
    //   website:
    //     "https://www.deere.com/en/hay-forage/harvesting/self-propelled-forage-harvesters/",
    // },
    // {
    //   // id: "59",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Power steering increases productivity for long working hours,Side Shift Gear Levers for ease of operation and higher comfort",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "5036D",
    //   price: "Contact Dealer",
    //   prebuilt: "Yes",
    //   image:
    //     "https://www.deere.co.in/assets/images/images/5050d_tractor_large_1d4d9d02bdedcff9452193a7843884aa9058dc44.png",
    //   youtube: "https://youtu.be/GOjrRnxGzcw",
    //   website:
    //     "https://www.deere.co.in/en/tractors/d-series-tractors/5036d-tractor/",
    // },
    // {
    //   // id: "60",
    //   name: "Tractor",
    //   crop: {
    //     All: "All",
    //   },
    //   crops: ["All"],
    //   use: "Land preparation",
    //   description:
    //     "Packed with power, this heavy-duty agricultural tractor is best suited for both dry and wet land cultivation",
    //   phaseofcrop: "Land preparation",
    //   manufactured: "John Deere",
    //   model: "5105",
    //   price: "Contact Dealer",
    //   prebuilt: "Yes",
    //   image:
    //     "https://5.imimg.com/data5/PD/UO/MD/SELLER-31851778/john-deere-5150-tractor-500x500.jpg",
    //   youtube: "https://youtu.be/cJI216BnWfw",
    //   website:
    //     "https://www.deere.co.in/en/tractors/d-series-tractors/5105-tractor/",
    // },
    // {
    //   // id: "54",
    //   name: "",
    //   crop: "",
    //   use: "",
    //   description: "",
    //   phaseofcrop: "",
    //   manufactured: "",
    //   model: "",
    //   price: 120000,
    //   prebuilt: "",
    //   image: "",
    //   youtube: "",
    //   website: "",
    // },
  ],
};
