module.exports = {
  machinery: [
    {
      // id: "1",
      name: "Combine Harvester",
      crop: "Paddy",
      use: "Cutting of paddy,Sorting and cleaning grains",
      description: "Self propelled full feeding with auger spike threshing",
      phaseofcrop: "Harvesting",
      manufactured: "Darsh Palesse",
      price: 2410000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/SELLER/Default/2020/8/RI/YG/DX/112029108/gt-6-500x500.png",
      youtube: "https://youtu.be/xi6PwVlM74U",
      website:
        "https://www.indiamart.com/proddetail/gomselmash-paddy-combine-harvester-22562420997.html",
    },

    {
      // id: "2",
      name: "Tractor",
      crop: "All",
      use: "Land preparation",
      description:
        "Exception built and performance on rugged and unforgiving terrains",
      phaseofcrop: "Cultivation",
      manufactured: "Mahindra",
      price: 450000,
      prebuilt: "yes",
      image:
        "https://www.tractorjunction.com/assets/images/upload/575-di-1586002666.jpg",
      youtube: "https://youtu.be/4zZR-D0MbtA",
      website: "https://www.mahindratractor.com/",
    },
    {
      // id: "3",
      name: "Transplanter",
      crop: "Potato",
      use: "Transplanting seedlings into the field",
      description:
        "Automatic float adjustment mechanism for uniform depths for high yield.",
      phaseofcrop: "Sowing",
      manufactured: "Mahindra",
      price: 230000,
      prebuilt: "yes",
      image:
        "https://img1.exportersindia.com/product_images/bc-full/2019/5/1045352/manual-rice-transplanter-1556713186-4884230.jpeg",
      youtube: "https://youtu.be/NGqlVSx-z1Y",
      website: "https://www.deere.co.in/en/implements/laser-leveler/",
    },
    {
      // id: "4",
      name: "Leveller",
      crop: "All",
      use: "Levelling of soil",
      description: "Laser guided soil leveller",
      phaseofcrop: "soil preparation",
      manufactured: "John Deere",
      price: 250000,
      prebuilt: "yes",
      image:
        "https://www.deere.co.in/assets/images/region-1/products/implements/Laser_Leveler_large_e90a1ebc5a42890049433807f52aaf9fe647a244.png",
      youtube: "https://youtu.be/RXVN2oZmNf4",
      website: "https://www.deere.co.in/en/implements/laser-leveler/",
    },
    {
      // id: "5",
      name: "Rice cutting machine",
      crop: "wheat",
      use: "cutting grains from the crop",
      description: "is suitable for cutting all kinds of crops",
      phaseofcrop: "Harvesting",
      manufactured: "Vardhman",
      price: 115000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/ND/FB/MY-10411868/2fd-soya-vardhman-power-reapers-500x500.jpg",
      youtube: "https://youtu.be/RXVN2oZmNf4",
      website: "https://www.deere.co.in/en/implements/laser-leveler/",
    },
    {
      // id: "6",
      name: "Destoner",
      crop: "Paddy",
      use: "Separating stones and broken rice from the rice",
      description: "Is suitable for all kind of grains",
      phaseofcrop: "After harvesting",
      manufactured: "Damodar process plant pvt ltd",
      price: 110000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/LR/OB/HZ/SELLER-9040957/tea-destoner-500x500.jpg",
      youtube: "https://youtu.be/1c9w3JrxcGc",
      website: "",
    },
    {
      // id: "7",
      name: "Rice mill",
      crop: "Paddy",
      use: "Paddy is processed to rice",
      description: "Produce edible milled rice and separates the husk",
      phaseofcrop: "After harvesting",
      manufactured: "Agripro",
      price: 190000,
      prebuilt: "yes",
      image:
        "https://i.pinimg.com/564x/18/e6/b7/18e6b7c930b20846d04204a8fb6370f2.jpg",
      youtube: "https://youtu.be/TfD5Uhg3JHo",
      website: "",
    },
    {
      // id: "8",
      name: "Polisher",
      crop: "Paddy",
      use: "Transforming brown rice into white rice",
      description: "Easy to use, operate and carry. Low maintenance.",
      phaseofcrop: "After harvesting",
      manufactured: "Sun Agro",
      price: 25000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/NQ/EU/QT/ANDROID-6423016/product-jpeg-500x500.jpg",
      youtube: "https://youtu.be/g1TOIhusP_0",
      website: "http://www.sunagrobhilai.com/",
    },
    {
      // id: "9",
      name: "Furrow Opener",
      crop: "All",
      use: "Makes straight and deep furrow by pressuring with opening blade",
      description: "Furrow Opener Cum Ridger",
      phaseofcrop: " seedling",
      manufactured: "Sudha Agro Industries",
      price: 38000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/MI/GT/ND/SELLER-2292693/7-tyne-tractor-operated-cultivator-500x500.jpg",
      youtube: "",
      website: "",
    },
    {
      // id: "10",
      name: "Plough",
      crop: "All",
      use: "Loosening or turning the soil before sowing seed or planting",
      description:
        "Large farming tool with sharp blades which is pulled across the soil",
      phaseofcrop: "Land preparation",
      manufactured: "Bharat steel works",
      price: 18500,
      prebuilt: "yes",
      image:
        "https://3.imimg.com/data3/KQ/IF/MY-7704388/bedder-plough-500x500.jpg",
      youtube: "https://youtu.be/MgIDOovFT5A",
      website: "https://www.bharatsteelwork.com/",
    },
    {
      // id: "11",
      name: "Rice Huller",
      crop: "Paddy",
      use: "Automate the process of removing the chaff of grains of rice.",
      description:
        "Uses an abrasive rotating disk to first remove the husk before passing the grain to conical rollers",
      phaseofcrop: "Harvesting",
      manufactured: "Thomas International",
      price: 16000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/HZ/JZ/BV/SELLER-3213215/rice-huller-with-polisher-blower-attached-500x500.jpg",
      youtube: "https://youtu.be/RGA77K6XUzw",
      website: "https://www.thomaseximp.com/rice%20%26%20maize.html",
    },
    {
      // id: "12",
      name: "Thresher",
      crop: "All",
      use:
        "Threshes the grain by beating the plant to make the seeds fall out.",
      description: "Suitable for multi crop threshing",
      phaseofcrop: "Harvesting",
      manufactured: "Mahindra",
      price: 135000,
      prebuilt: "yes",
      image:
        "https://5.imimg.com/data5/SELLER/Default/2020/9/PY/PF/NJ/15747168/thresher-m55-500x500.jpg",
      youtube: "https://youtu.be/ZxvkBNPlwKQ",
      website:
        "https://www.machinenmotor.com/details/mahindra-mild-steel-multi-crop-thresh",
    },
    {
      // id: "13",
      name: "Weeder",
      crop: "All",
      use: "Removing weeds and clearing the soil",
      description: "Adjustable handlebar to meet different requirements",
      phaseofcrop: "Cultivation",
      manufactured: "Agripro",
      price: 27500,
      prebuilt: "yes",
      image:
        "https://cdn1.industrybuying.com/products_medium/agriculture-garden-landscaping/tillers-and-cultivator/cultivator/AGR.CUL.42018780_1547458842273.jpg",
      youtube: "https://youtu.be/rV3b2ucMTls",
      website: "https://www.agri-pro.com/",
    },
    // {
    //   id: "6",
    //   type: "machinery",
    //   name: "Item",
    //   image:
    //     "https://cdn.pixabay.com/photo/2018/10/03/21/57/cabbage-3722498_960_720.jpg",
    //   comment:
    //     " Lizards are a widespread group of squamate reptiles, with over 6,000 species, ranging across all continents except Antarctica",
    // },
  ],
};
